# @package _group_
name: adv-only

# Hyperparamaters for training
train_batch_size: 256
test_batch_size: 256
lr: 0.005
epochs: 100

log_interval: 100 # in iterations

attack: pgd # method for adversarial example generation

# Hyperparameters for PGD/FGSM
eps: 0.25 # max perturbation. (PGD, FGSM)
alpha: 0.01 # step size (PGD only)
num_iter: 25 # number of steps (PGD only)
randomize: True # whether or not the initiazation of PGD example is random (PGD only)

# Hyperparameters for watermarking
wm_train: False # Flag for watermarking training
trigger_size: 1
wm_batch_size: 1
