# @package _group_
name: dp-only

lr: 0.005
epochs: 100
train_batch_size: 256
test_batch_size: 256

log_interval: 100 # in iterations

use_dp: True # Flag for training with DP
eps: 3.0
delta: 1e-3
max_grad_norm: 1.0

# Hyperparameters for watermarking
wm_train: False # Flag for watermarking training
wm_batch_size: 1
trigger_size: 1
