# @package _group_
name: dp-wm

lr: 0.005
epochs: 100
train_batch_size: 64
test_batch_size: 128

log_interval: 100 # in iterations

use_dp: True # Flag for training with DP
eps: 3.0
delta: 1e-3
max_grad_norm: 1.0

# Hyperparameters for watermarking
wm_train: True # Flag for watermarking training
wm_batch_size: 16
trigger_size: 100
