# @package _group_
name: wm-only

lr: 0.005
epochs: 100

log_interval: 100 # in iterations

use_dp: False # Flag for training with DP
eps: 1.0
delta: 1e-3
max_grad_norm: 1.0

# Hyperparameters for watermarking
wm_train: True # Flag for watermarking training
train_batch_size: 64
test_batch_size: 128
wm_batch_size: 16
trigger_size: 100
